drop_occupied:
  enable: true
  occupied_ids: [
      "UA.15_1",  # Luhansk
      "UA.6_1",   # Donetsk
      "UA.26_1",  # Zaporizhzhia
      "UA.9_1",   # Kherson
      "UA.4_1",   # Crimea
      "UA.20_1",  # Sevastopol
  ] # List of GADM IDs

generation_war_damages:
  enable: true
  damage_percentage_by_carrier: [ 
    nuclear: 0, # Occupied infrastructure is handled by a separate rule
    thermal: 0.89,
    CCGT: 0.51,
    hydro: 0.54,
    PHS: 0.17,
    wind: 0,
    solar: 0,
  ] # Current values are based on eye measurements from a figure where the shares were not marked explicitly, needs to be verified more thoroughly
  preferred_damage_distribution: [
    UA.5_1: 0.21, # Dnipropetrovsk
    UA.8_1: 0.11, # Kharkiv
    UA.21_1: 0.05, # Sumy
    UA.2_1: 0.19, # Chernihiv
    UA.17_1: 0.01, # Odesa
    UA.16_1: 0.03, # Mykolaiv
    UA.18_1: 0.02, # Poltava
    UA.11_1: 0.00, # Kyiv City
    UA.12_1: 0.13, # Kyiv Oblast
    UA.14_1: 0.02, # Lviv
    UA.1_1: 0.02, # Cherkasy
    UA.13_1: 0.02, # Kirohovhrad
    UA.24_1: 0.05, # Vinnytsia
    UA.7_1: 0.11, # Ivano-Frankivsk
    UA.27_1: 0.00, # Zhytomyr
    UA.19_1: 0.01, # Rivne
    UA.10_1: 0.01, # Khmenlytskyi
    UA.22_1: 0.00, # Ternopil
    UA.3_1: 0.01, # Chernivtsi
    UA.25_1: 0.0, # Volyn
    UA.23_1: 0.00, # Zakarpattia
  ] # Values should add up to 1

load_adjustment:
  enable: true

  base_industrial_loads: [ 
    UA.5_1: 22.01, # Dnipropetrovsk
    UA.8_1: 3.6, # Kharkiv
    UA.21_1: 1.20, # Sumy
    UA.2_1: 0.79, # Chernihiv
    UA.17_1: 2.32, # Odesa
    UA.16_1: 3.30, # Mykolaiv
    UA.18_1: 3.82, # Poltava
    UA.11_1: 5.55, # Kyiv City
    UA.12_1: 3.01, # Kyiv Oblast
    UA.14_1: 2.3, # Lviv
    UA.1_1: 1.77, # Cherkasy
    UA.13_1: 2.28, # Kirohovhrad
    UA.24_1: 1.73, # Vinnytsia
    UA.7_1: 2.58, # Ivano-Frankivsk
    UA.27_1: 1.27, # Zhytomyr
    UA.19_1: 2.68, # Rivne
    UA.10_1: 1.71, # Khmenlytskyi
    UA.22_1: 0.42, # Ternopil
    UA.3_1: 1.90, # Chernivtsi
    UA.25_1: 0.68, # Volyn
    UA.23_1: 0.44, # Zakarpattia
  ] # Values are in TWh

  industrial_adjustment_coefficients: [
    UA.5_1: 0.53, # Dnipropetrovsk
    UA.8_1: 0.50, # Kharkiv
    UA.21_1: 0.51, # Sumy
    UA.2_1: 0.29, # Chernihiv
    UA.17_1: 0.54, # Odesa
    UA.16_1: 0.44, # Mykolaiv
    UA.18_1: 0.56, # Poltava
    UA.11_1: 0.67, # Kyiv City
    UA.12_1: 0.69, # Kyiv Oblast
    UA.14_1: 0.85, # Lviv
    UA.1_1: 0.70, # Cherkasy
    UA.13_1: 0.63, # Kirohovhrad
    UA.24_1: 0.68, # Vinnytsia
    UA.7_1: 0.53, # Ivano-Frankivsk
    UA.27_1: 0.64, # Zhytomyr
    UA.19_1: 0.67, # Rivne
    UA.10_1: 0.60, # Khmenlytskyi
    UA.22_1: 0.67, # Ternopil
    UA.3_1: 0.78, # Chernivtsi
    UA.25_1: 0.80, # Volyn
    UA.23_1: 0.68, # Zakarpattia
  ] # Coefficients used to adjust the base industrial loads

  population_adjustment_coefficients: [
    UA.5_1: 1.10, # Dnipropetrovsk
    UA.8_1: 0.96, # Kharkiv
    UA.21_1: 1.00, # Sumy
    UA.2_1: 1.19, # Chernihiv
    UA.17_1: 0.88, # Odesa
    UA.16_1: 1.02, # Mykolaiv
    UA.18_1: 0.92, # Poltava
    UA.11_1: 1.09, # Kyiv City
    UA.12_1: 1.32, # Kyiv Oblast
    UA.14_1: 0.73, # Lviv
    UA.1_1: 0.92, # Cherkasy
    UA.13_1: 0.94, # Kirohovhrad
    UA.24_1: 0.85, # Vinnytsia
    UA.7_1: 1.04, # Ivano-Frankivsk
    UA.27_1: 0.84, # Zhytomyr
    UA.19_1: 0.9, # Rivne
    UA.10_1: 0.9, # Khmenlytskyi
    UA.22_1: 1.04, # Ternopil
    UA.3_1: 1.12, # Chernivtsi
    UA.25_1: 1.04, # Volyn
    UA.23_1: 1.2, # Zakarpattia
  ] # Coefficients used to adjust the base household loads

cross_border:
  enable: false
  carrier: cross-border
  ntc_gw: 1.6
  marginal_cost: 60
  p_nom_mw: 1000000
  buses: ["89", "55", "1469"] # Default buses near EU neighbours

outages:
  enable: false
  buses: []     # bus IDs as strings 
  lines: []      # line IDs as strings 